  version: 2
  updates:
    - package-ecosystem: github-actions
      directory: /
      open-pull-requests-limit: 5
      schedule:
        interval: daily
        time: '07:00'
        timezone: Europe/Berlin

    - package-ecosystem: gomod
      directory: /
      open-pull-requests-limit: 5
      schedule:
        interval: daily
        time: '07:00'
        timezone: Europe/Berlin