# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - '*'
      
#Environment variables required for the tests
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build and Test
      run: make test
    - name: Analyze with Sonar
      uses: sonarsource/sonarcloud-github-action@master
